"""baseline schema

Revision ID: a55b3168b406
Revises:
Create Date: 2026-06-25 03:18:24.004608+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a55b3168b406"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "setting",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("setting", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_setting_key"), ["key"], unique=True)

    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("host_voice_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["host_voice_id"], ["voice.id"], name="fk_user_host_voice_id", use_alter=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_username"), ["username"], unique=True)

    op.create_table(
        "episode",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "running", "succeeded", "failed", name="runstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("episode", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_episode_user_id"), ["user_id"], unique=False)

    op.create_table(
        "output_profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("document_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("return_details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("output_profile", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_output_profile_user_id"), ["user_id"], unique=False)

    op.create_table(
        "research_profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("research_field", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("research_topic", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("research_interests", sa.JSON(), nullable=False),
        sa.Column("research_focus", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("research_profile", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_research_profile_user_id"), ["user_id"], unique=False)

    op.create_table(
        "voice",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("provider_voice_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source", sa.Enum("stock", "cloned", name="voicesource", native_enum=False), nullable=False),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("role_hint", sa.Enum("host", "author", name="speakerrole", native_enum=False), nullable=True),
        sa.Column("sample_recording_ref", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("consent_granted", sa.Boolean(), nullable=False),
        sa.Column("consent_owner", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("consent_recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "paper",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_pdf_ref", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("extracted_text_ref", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("page_count", sa.Integer(), nullable=True),
        sa.Column("authors", sa.JSON(), nullable=False),
        sa.Column("doi", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("author_voice_id", sa.Integer(), nullable=True),
        sa.Column("chosen_profile_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_voice_id"],
            ["voice.id"],
        ),
        sa.ForeignKeyConstraint(
            ["chosen_profile_id"],
            ["research_profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("paper", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_paper_source_hash"), ["source_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_paper_user_id"), ["user_id"], unique=False)

    op.create_table(
        "podcast_asset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("episode_id", sa.Integer(), nullable=False),
        sa.Column("mp3_ref", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("narration_script", sa.JSON(), nullable=False),
        sa.Column("host_voice_id", sa.Integer(), nullable=True),
        sa.Column("model_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["episode.id"],
        ),
        sa.ForeignKeyConstraint(
            ["host_voice_id"],
            ["voice.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("podcast_asset", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_podcast_asset_episode_id"), ["episode_id"], unique=False)

    op.create_table(
        "episode_paper",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("episode_id", sa.Integer(), nullable=False),
        sa.Column("paper_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["episode.id"],
        ),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["paper.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("episode_id", "paper_id", name="uq_episode_paper"),
    )
    with op.batch_alter_table("episode_paper", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_episode_paper_episode_id"), ["episode_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_episode_paper_paper_id"), ["paper_id"], unique=False)

    op.create_table(
        "pipeline_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("paper_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "running", "succeeded", "failed", name="runstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("requested_stages", sa.JSON(), nullable=False),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["paper.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pipeline_run", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pipeline_run_paper_id"), ["paper_id"], unique=False)

    op.create_table(
        "summary",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("paper_id", sa.Integer(), nullable=False),
        sa.Column("overall_summary", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("key_findings", sa.JSON(), nullable=False),
        sa.Column("contributions", sa.JSON(), nullable=False),
        sa.Column("gaps_and_limitations", sa.JSON(), nullable=False),
        sa.Column("methods", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("relevance_to_profile", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("model_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("prompt_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("profile_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["paper.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("summary", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_summary_content_hash"), ["content_hash"], unique=False)
        batch_op.create_index(batch_op.f("ix_summary_paper_id"), ["paper_id"], unique=False)

    op.create_table(
        "report_asset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("paper_id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=True),
        sa.Column("pdf_ref", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("template_version", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["paper_id"],
            ["paper.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["pipeline_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("report_asset", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_report_asset_paper_id"), ["paper_id"], unique=False)

    op.create_table(
        "stage_run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("stage_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("pending", "running", "succeeded", "failed", "skipped", name="stagestatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("cache_hit", sa.Boolean(), nullable=False),
        sa.Column("model_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("output_ref", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["pipeline_run.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("stage_run", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_stage_run_run_id"), ["run_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the mutual user<->voice FK (added post-create via use_alter) BEFORE the
    # user/voice tables, so the cycle unwinds cleanly on Postgres. SQLite cannot
    # ALTER-DROP a named constraint and drops FKs by rebuilding the table at
    # drop_table time, so the explicit drop is scoped to non-SQLite dialects.
    if op.get_bind().dialect.name != "sqlite":
        op.drop_constraint("fk_user_host_voice_id", "user", type_="foreignkey")

    with op.batch_alter_table("stage_run", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_stage_run_run_id"))

    op.drop_table("stage_run")
    with op.batch_alter_table("report_asset", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_report_asset_paper_id"))

    op.drop_table("report_asset")
    with op.batch_alter_table("summary", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_summary_paper_id"))
        batch_op.drop_index(batch_op.f("ix_summary_content_hash"))

    op.drop_table("summary")
    with op.batch_alter_table("pipeline_run", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pipeline_run_paper_id"))

    op.drop_table("pipeline_run")
    with op.batch_alter_table("episode_paper", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_episode_paper_paper_id"))
        batch_op.drop_index(batch_op.f("ix_episode_paper_episode_id"))

    op.drop_table("episode_paper")
    with op.batch_alter_table("podcast_asset", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_podcast_asset_episode_id"))

    op.drop_table("podcast_asset")
    with op.batch_alter_table("paper", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_paper_user_id"))
        batch_op.drop_index(batch_op.f("ix_paper_source_hash"))

    op.drop_table("paper")
    op.drop_table("voice")
    with op.batch_alter_table("research_profile", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_research_profile_user_id"))

    op.drop_table("research_profile")
    with op.batch_alter_table("output_profile", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_output_profile_user_id"))

    op.drop_table("output_profile")
    with op.batch_alter_table("episode", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_episode_user_id"))

    op.drop_table("episode")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_username"))

    op.drop_table("user")
    with op.batch_alter_table("setting", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_setting_key"))

    op.drop_table("setting")
    # ### end Alembic commands ###
