"""Tests for the Alembic baseline migration (Phase 2.0 + 2.2 Postgres-readiness).

Pure-Python (Alembic's command API, no external binary), so these run in the
default suite and actually gate schema drift:

* ``upgrade head`` then ``downgrade base`` runs clean on a fresh DB (the baseline
  builds the whole schema and reverses it cleanly);
* after ``upgrade head``, ``alembic check`` (autogenerate diff) detects no
  operations -- i.e. the SQLModel models and the committed migrations agree, so a
  drift between code and migrations fails here (mirrors the CI 2.2a step).

**Backend-agnostic (Phase 2.2).** These prove the *same* migrations apply on both
backends. The DB URL comes from the shared ``db_url`` fixture (``tests/conftest``),
which honours ``DATABASE_URL``: a per-test temp-file SQLite DB by default, or the
``postgresql+psycopg://...`` server in CI. The URL is injected into Alembic per-test
via ``-x dburl=...`` (the env reads it in ``migrations/env.py``), so tests never
touch the real ``DATA_DIR`` database. On Postgres the ``public`` schema is dropped +
recreated before each test (the temp file gives SQLite that isolation for free), so
a stale ``alembic_version`` never leaks between migration tests.
"""

from __future__ import annotations

from collections.abc import Iterator
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import inspect

from downlow.adapters.db.engine import create_db_engine
from tests.conftest import _clean_postgres_schema, _is_postgres

PROJECT_ROOT = Path(__file__).resolve().parents[2]
ALEMBIC_INI = PROJECT_ROOT / "alembic.ini"


def _alembic_config(database_url: str) -> Config:
    """An Alembic config pointed at ``database_url`` via the ``-x dburl`` override."""
    config = Config(str(ALEMBIC_INI))
    config.set_main_option("script_location", str(PROJECT_ROOT / "migrations"))
    config.cmd_opts = type("Opts", (), {"x": [f"dburl={database_url}"]})()
    return config


@pytest.fixture
def migrate_url(db_url: str) -> Iterator[str]:
    """The shared backend-agnostic DB URL, with the Postgres schema cleaned first.

    Reuses the ``db_url`` fixture (SQLite temp file or the ``DATABASE_URL`` Postgres
    server). For Postgres it drops + recreates ``public`` so each migration test
    starts from an empty DB with no leftover ``alembic_version``.
    """
    if _is_postgres(db_url):
        engine = create_db_engine(db_url)
        try:
            _clean_postgres_schema(engine)
        finally:
            engine.dispose()
    yield db_url


def test_upgrade_head_builds_the_full_schema(migrate_url: str) -> None:
    command.upgrade(_alembic_config(migrate_url), "head")

    engine = create_db_engine(migrate_url)
    try:
        tables = set(inspect(engine).get_table_names())
    finally:
        engine.dispose()

    expected = {
        "user",
        "research_profile",
        "output_profile",
        "paper",
        "summary",
        "report_asset",
        "episode",
        "episode_paper",
        "podcast_asset",
        "pipeline_run",
        "stage_run",
        "voice",
        "setting",
    }
    assert expected <= tables, f"missing tables: {expected - tables}"


def test_downgrade_base_is_clean(migrate_url: str) -> None:
    config = _alembic_config(migrate_url)
    command.upgrade(config, "head")
    command.downgrade(config, "base")

    engine = create_db_engine(migrate_url)
    try:
        remaining = set(inspect(engine).get_table_names())
    finally:
        engine.dispose()

    # Only Alembic's own bookkeeping table may remain; no app tables.
    assert remaining <= {"alembic_version"}, f"downgrade left tables: {remaining - {'alembic_version'}}"


def test_models_and_migrations_agree_no_drift(migrate_url: str) -> None:
    """The 2.2a drift gate: autogenerate against the migrated DB finds nothing.

    ``command.check`` raises :class:`AutogenerateDiffsDetected` when the SQLModel
    models diverge from the committed migrations, so a missing/extra column or index
    fails this test (and the equivalent CI step). Runs on whichever backend
    ``DATABASE_URL`` selects, so cross-backend drift (a type that autogenerates
    differently on Postgres) is caught in the Postgres CI job.
    """
    config = _alembic_config(migrate_url)
    command.upgrade(config, "head")
    try:
        command.check(config)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - failure path
        pytest.fail(f"schema drift between models and migrations:\n{exc}")
